In [1]:
import numpy as np
import pandas as pd

In [2]:
#CREATING A DATAFRAME

In [5]:
data={
    'Name':['John','Lucky','Max','Ronny'],
    'Age':[18,21,28,30],
    'City':['Pune','Mumbai','Nagpur','Nashik'],
    'Salary':[90000,86000,50000,45000]
}
df=pd.DataFrame(data)

In [6]:
df

    Name  Age    City  Salary
0   John   18    Pune   90000
1  Lucky   21  Mumbai   86000
2    Max   28  Nagpur   50000
3  Ronny   30  Nashik   45000

In [9]:
data_list=[
    ['John',18,'Pune',90000],
    ['Lucky',21,'Mumbai',86000],
    ['Max',28,'Nagpur',50000],
    ['Ronny',30,'Nashik',45000]
]
df2=pd.DataFrame(data_list)
columns=['Name','Age','City','Salary']
df2=pd.DataFrame(data_list,columns=columns)
df2

    Name  Age    City  Salary
0   John   18    Pune   90000
1  Lucky   21  Mumbai   86000
2    Max   28  Nagpur   50000
3  Ronny   30  Nashik   45000

In [ ]:
#SELECTION AND INDEXING OF COLUMNS

In [10]:
df['Name']

0     John
1    Lucky
2      Max
3    Ronny
Name: Name, dtype: object

In [11]:
df[['Name','City']]

    Name    City
0   John    Pune
1  Lucky  Mumbai
2    Max  Nagpur
3  Ronny  Nashik

In [ ]:
#CREATING A NEW COLUMN

In [12]:
df2['Designation']=['Doctor','Eng.','Doctor','Eng.']

In [13]:
df2

    Name  Age    City  Salary Designation
0   John   18    Pune   90000      Doctor
1  Lucky   21  Mumbai   86000        Eng.
2    Max   28  Nagpur   50000      Doctor
3  Ronny   30  Nashik   45000        Eng.

In [ ]:
#REMOVING COLUMN

In [14]:
df2.drop('Designation',axis=1,inplace=True) #permenant delete

In [19]:
df2

    Name  Age    City  Salary
0   John   18    Pune   90000
1  Lucky   21  Mumbai   86000
2    Max   28  Nagpur   50000
3  Ronny   30  Nashik   45000

In [20]:
df2.drop(['Salary','City'],axis=1) #Temporary delete

    Name  Age
0   John   18
1  Lucky   21
2    Max   28
3  Ronny   30

In [21]:
df2.drop(0,axis=0)

    Name  Age    City  Salary
1  Lucky   21  Mumbai   86000
2    Max   28  Nagpur   50000
3  Ronny   30  Nashik   45000

In [ ]:
#SELECTING ROWS

In [24]:
df2.loc[[0,1]]

    Name  Age    City  Salary
0   John   18    Pune   90000
1  Lucky   21  Mumbai   86000

In [25]:
df2.iloc[3]

Name       Ronny
Age           30
City      Nashik
Salary     45000
Name: 3, dtype: object

In [ ]:
#SELECTING SUBSETS OF ROWS AND COLUMNS

In [28]:
df2.loc[[0,1]][['Name','City']]

    Name    City
0   John    Pune
1  Lucky  Mumbai

In [ ]:
#CONDITIONAL SELECTION

In [30]:
#I ONLY WANT TO SEE THOSE PEOPLE WHOSE AGE IS ABOVE OR EQUAL TO 20
df2[df2['Age'] >=20]

    Name  Age    City  Salary
1  Lucky   21  Mumbai   86000
2    Max   28  Nagpur   50000
3  Ronny   30  Nashik   45000

In [36]:
#I ONLY WANT TO SEE THOSE PEOPLE WHOSE AGE IS ABOVE OR EQUAL TO 20 AND THERE CITY MUST BE MUMBAI
df2[(df2['Age'] > 20) & (df2['City']=='Mumbai')]

    Name  Age    City  Salary
1  Lucky   21  Mumbai   86000