In [3]:
import numpy as np
import pandas as pd

In [32]:
#DATAFRAME -1
employees=pd.DataFrame({
    'Employee_id':[1,2,3,4,5],
    'Nama':['John','Lucky','Ronny','Max','Arnav'],
    'Department':['HR','IT','Finance','IT','HR']
})

#DATAFRAME-2
salaries=pd.DataFrame({
    'Employee_id':[1,2,3,4,5],
    'Salary':[90000,70000,65000,73000,90000],
    'Bonus':[15000,10000,8000,10000,15000]
})

In [33]:
employees

   Employee_id   Nama Department
0            1   John         HR
1            2  Lucky         IT
2            3  Ronny    Finance
3            4    Max         IT
4            5  Arnav         HR

In [34]:
salaries

   Employee_id  Salary  Bonus
0            1   90000  15000
1            2   70000  10000
2            3   65000   8000
3            4   73000  10000
4            5   90000  15000

In [ ]:
#MERGING 2 DATAFRAMES

In [35]:
pd.merge(employees,salaries)

   Employee_id   Nama Department  Salary  Bonus
0            1   John         HR   90000  15000
1            2  Lucky         IT   70000  10000
2            3  Ronny    Finance   65000   8000
3            4    Max         IT   73000  10000
4            5  Arnav         HR   90000  15000

In [36]:
#DATAFRAME -1
employees=pd.DataFrame({
    'Employee_id':[1,2,3,4,5],
    'Nama':['John','Lucky','Ronny','Max','Arnav'],
    'Department':['HR','IT','Finance','IT','HR']
})

#DATAFRAME-2
salaries=pd.DataFrame({
    'Employee_id':[1,2,3,6,7],
    'Salary':[90000,70000,65000,73000,90000],
    'Bonus':[15000,10000,8000,10000,15000]
})

In [38]:
pd.merge(employees,salaries,on='Employee_id',how='inner')

   Employee_id   Nama Department  Salary  Bonus
0            1   John         HR   90000  15000
1            2  Lucky         IT   70000  10000
2            3  Ronny    Finance   65000   8000

In [31]:
pd.merge(employees,salaries,on='Employee_id',how='outer')

   Employee_id   Nama Department   Salary    Bonus
0            1   John         HR  90000.0  15000.0
1            2  Lucky         IT  70000.0  10000.0
2            3  Ronny    Finance  65000.0   8000.0
3            4    Max         IT      NaN      NaN
4            5  Arnav         HR      NaN      NaN
5            6    NaN        NaN  73000.0  10000.0
6            7    NaN        NaN  90000.0  15000.0

In [39]:
pd.merge(employees,salaries,on='Employee_id',how='left')

   Employee_id   Nama Department   Salary    Bonus
0            1   John         HR  90000.0  15000.0
1            2  Lucky         IT  70000.0  10000.0
2            3  Ronny    Finance  65000.0   8000.0
3            4    Max         IT      NaN      NaN
4            5  Arnav         HR      NaN      NaN

In [40]:
pd.merge(employees,salaries,on='Employee_id',how='right')

   Employee_id   Nama Department  Salary  Bonus
0            1   John         HR   90000  15000
1            2  Lucky         IT   70000  10000
2            3  Ronny    Finance   65000   8000
3            6    NaN        NaN   73000  10000
4            7    NaN        NaN   90000  15000

In [ ]:
#CONCATINATION OF 2 FRAMES

In [41]:
df1=pd.DataFrame({
    "A":['A0','A1','A2'],
    "B":['B0','B1','B2'],
    "C":['C0','C1','C2'],
})
df2=pd.DataFrame({
    "A":['A3','A4','A5'],
    "B":['B3','B4','B5'],
    "C":['C3','C4','C5'],
})

In [42]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [43]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [45]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [46]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [48]:
#JOINING 2 DATAFRAMES

In [49]:
df1=pd.DataFrame({
    'Name':['John','Raj','Lucky']
},index=[1,2,3])

df2=pd.DataFrame({
    'score':[90,78,81]
},index=[2,3,4])

In [50]:
df1

    Name
1   John
2    Raj
3  Lucky

In [51]:
df2

   score
2     90
3     78
4     81

In [52]:
df1.join(df2)

    Name  score
1   John    NaN
2    Raj   90.0
3  Lucky   78.0

In [53]:
df1.join(df2,how='outer')

    Name  score
1   John    NaN
2    Raj   90.0
3  Lucky   78.0
4    NaN   81.0