In [1]:
import numpy as np
import pandas as pd

In [4]:
#FINDING MISSING DATA

In [8]:
data={
    'A':[1,2,3,4,5],
    'B':[1,np.nan,3,4,5],
    'C':[1,2,np.nan,np.nan,5],
    'D':[1,np.nan,3,np.nan,np.nan]
}
df=pd.DataFrame(data)

In [9]:
df

   A    B    C    D
0  1  1.0  1.0  1.0
1  2  NaN  2.0  NaN
2  3  3.0  NaN  3.0
3  4  4.0  NaN  NaN
4  5  5.0  5.0  NaN

In [5]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False   True  False   True
2  False  False   True  False
3   True  False   True   True
4  False  False  False   True

In [10]:
df.isna().sum()

A    0
B    1
C    2
D    3
dtype: int64

In [11]:
df.isna().any()

A    False
B     True
C     True
D     True
dtype: bool

In [ ]:
#REMOVING MISSING DATA

In [12]:
df.dropna()

   A    B    C    D
0  1  1.0  1.0  1.0

In [13]:
df

   A    B    C    D
0  1  1.0  1.0  1.0
1  2  NaN  2.0  NaN
2  3  3.0  NaN  3.0
3  4  4.0  NaN  NaN
4  5  5.0  5.0  NaN

In [14]:
df.dropna(thresh=3)

   A    B    C    D
0  1  1.0  1.0  1.0
2  3  3.0  NaN  3.0
4  5  5.0  5.0  NaN

In [ ]:
#FILLING THE MISSING DATA

In [15]:
df.fillna(0)

   A    B    C    D
0  1  1.0  1.0  1.0
1  2  0.0  2.0  0.0
2  3  3.0  0.0  3.0
3  4  4.0  0.0  0.0
4  5  5.0  5.0  0.0

In [16]:
values={'A':0,'B':11,'C':35,'D':49}
df.fillna(value=values)

   A     B     C     D
0  1   1.0   1.0   1.0
1  2  11.0   2.0  49.0
2  3   3.0  35.0   3.0
3  4   4.0  35.0  49.0
4  5   5.0   5.0  49.0

In [18]:
df

   A    B    C    D
0  1  1.0  1.0  1.0
1  2  NaN  2.0  NaN
2  3  3.0  NaN  3.0
3  4  4.0  NaN  NaN
4  5  5.0  5.0  NaN

In [19]:
df.fillna(df.mean())

   A     B         C    D
0  1  1.00  1.000000  1.0
1  2  3.25  2.000000  2.0
2  3  3.00  2.666667  3.0
3  4  4.00  2.666667  2.0
4  5  5.00  5.000000  2.0